### PR TITLE
fix: issue with copy-button in patternhub

### PR DESCRIPTION
**Pull request by nmerget**
## Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Refactoring (fix on existing components or architectural decisions)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation Update (if none of the other choices apply)

### CODE REVIEW

**Comment by mfranzke** [comment]
@nmerget what is the issue in this one? I couldn't have identified any difference.

**Comment by nmerget** [comment]
> @nmerget what is the issue in this one? I couldn't have identified any difference.

The copy button in show-code isn't clickable

**Comment by mfranzke** [comment]
> > @nmerget what is the issue in this one? I couldn't have identified any difference.
> 
> The copy button in show-code isn't clickable

to me it looks like that it's not just the button, but some more parts of the UI:
image

**Comment by nmerget** [comment]
> > > @nmerget what is the issue in this one? I couldn't have identified any difference.
> > 
> > 
> > The copy button in show-code isn't clickable
> 
> to me it looks like that it's not just the button, but some more parts of the UI (on narrower viewports): image

Thanks for the hint, fixed it

**Pull request merged**
