### PR TITLE
refactor: making vue a devDependency

### PR DESCRIPTION
**Pull request by mfranzke**
## Proposed changes

I can't identify a reason why "vue" would need to be a Dependency within our package.

Resolves https://github.com/db-ui/mono/issues/3299

## Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Refactoring (fix on existing components or architectural decisions)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation Update (if none of the other choices apply)

### CODE REVIEW

**Comment by mfranzke** [comment]
@schneisn I've just moved "vue" to be a devDepenency within our package, as I couldn't identify a reason for being a "dependency". Could you please retest whether everything still works as expected with the pre-release `[@db-ui/v-components@0.5.0-0-ad6b54c](https://www.npmjs.com/package/@db-ui/v-components/v/0.5.0-0-ad6b54c)`

**Comment by schneisn** [comment]
@mfranzke I tested the pre-relase and the error does not occur anymore. Thanks!

**Comment by mfranzke** [comment]
> @mfranzke I tested the pre-relase and the error does not occur anymore. Thanks!

great, thanks a lot to you !

**Comment by mfranzke** [comment]
@schneisn we're planning to release this into the stable channel with version 0.5.0 that we're planning for monday, 28th.

**Review by nmerget — APPROVED** [review]

**Review by nmerget — APPROVED** [review]

**Pull request merged**
