### PR TITLE
refactor: enabled firefox "support" again

### PR DESCRIPTION
**Pull request by mfranzke**
## Proposed changes

We could remove our warning for Firefox browser support now. And include the tests as well.

_to get merged on 19th of December, the next Firefox release date: https://whattrainisitnow.com/release/?version=121_

Resolves https://github.com/db-ui/mono/issues/1009

## Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Refactoring (fix on existing components or architectural decisions)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [x] Documentation Update (if none of the other choices apply)

### CODE REVIEW

**Comment by nmerget** [comment]
[Playwright](https://github.com/microsoft/playwright?tab=readme-ov-file#documentation--api-reference) has still 120 as firefox version, we need to wait until they updated the browser as well

**Comment by mfranzke** [comment]
> [Playwright](https://github.com/microsoft/playwright?tab=readme-ov-file#documentation--api-reference) has still 120 as firefox version, we need to wait until they updated the browser as well

… or switch to Firefox Beta for the moment just to keep this rolling.

**Comment by mfranzke** [comment]
> [Playwright](https://github.com/microsoft/playwright?tab=readme-ov-file#documentation--api-reference) has still 120 as firefox version, we need to wait until they updated the browser as well

[Firefox 121 has been introduced to playwright](https://github.com/microsoft/playwright/pull/28882) so we could use it with the next release of playwright. I know, that you [still identified problems with Node 20 with playwright now uses](https://github.com/db-ui/mono/pull/2042).

**Comment by mfranzke** [comment]
> > > [Playwright](https://github.com/microsoft/playwright?tab=readme-ov-file#documentation--api-reference) has still 120 as firefox version, we need to wait until they updated the browser as well
> > 
> > 
> > @nmerget [Firefox 121 has been introduced to playwright](https://github.com/microsoft/playwright/pull/28882) so we could use it with the next release of playwright. I know, that you [still identified problems with Node 20 with playwright now uses](https://github.com/db-ui/mono/pull/2042).
> 
> I think we need to solve #1826 as well, before we can migrate

that's my fear as well.

**Comment by nmerget** [comment]
> > [Playwright](https://github.com/microsoft/playwright?tab=readme-ov-file#documentation--api-reference) has still 120 as firefox version, we need to wait until they updated the browser as well
> 
> @nmerget [Firefox 121 has been introduced to playwright](https://github.com/microsoft/playwright/pull/28882) so we could use it with the next release of playwright. I know, that you [still identified problems with Node 20 with playwright now uses](https://github.com/db-ui/mono/pull/2042).

We need to wait for the [release](https://www.npmjs.com/package/@playwright/test)

**Comment by mfranzke** [comment]
> > > [Playwright](https://github.com/microsoft/playwright?tab=readme-ov-file#documentation--api-reference) has still 120 as firefox version, we need to wait until they updated the browser as well
> > 
> > 
> > @nmerget [Firefox 121 has been introduced to playwright](https://github.com/microsoft/playwright/pull/28882) so we could use it with the next release of playwright. I know, that you [still identified problems with Node 20 with playwright now uses](https://github.com/db-ui/mono/pull/2042).
> 
> We need to wait for the [release](https://www.npmjs.com/package/@playwright/test)

but than we could actually extract the new playwright update scripts and "test" it when this new update gets released.

**Comment by mfranzke** [comment]
> > > [Playwright](https://github.com/microsoft/playwright?tab=readme-ov-file#documentation--api-reference) has still 120 as firefox version, we need to wait until they updated the browser as well
> > 
> > 
> > @nmerget [Firefox 121 has been introduced to playwright](https://github.com/microsoft/playwright/pull/28882) so we could use it with the next release of playwright. I know, that you [still identified problems with Node 20 with playwright now uses](https://github.com/db-ui/mono/pull/2042).
> 
> We need to wait for the [release](https://www.npmjs.com/package/@playwright/test)

It's not even beta so far: https://www.npmjs.com/package/@playwright/test?activeTab=versions

**Review by nmerget — APPROVED** [review]

**Pull request merged**
