### PR TITLE
feat: add simple outside of viewport handling for navigation item

### PR DESCRIPTION
**Pull request by nmerget**
## Proposed changes

The navigation was very simple without any JS to check the boundaries of the viewport.
This is a simple solution to check if a sub-navigation is outside of the viewport.

## Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Refactoring (fix on existing components or architectural decisions)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation Update (if none of the other choices apply)

### CODE REVIEW

**Comment by mfranzke** [comment]
@nmerget is this PR obsolete?

**Comment by nmerget** [comment]
Somehow it's already merged. But the functionality isn't working :S

**Comment by mfranzke** [comment]
> Somehow it's already merged. But the functionality isn't working :S

"somehow" it has been integrated with this commit: https://github.com/db-ui/mono/commit/1803f94d10c5ad65f6d3569bbd64dfd69ee2cc0e ;-)

**Comment by nmerget** [comment]
Already merged to main

**Pull request closed without merging**
