### PR TITLE
fix: issue with patternhub not having a fallback for `not found` pages

### PR DESCRIPTION
**Pull request by nmerget**
## Proposed changes

Fix issue for Marketingportal, resolves https://github.com/db-ui/mono/issues/1546

## Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Refactoring (fix on existing components or architectural decisions)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation Update (if none of the other choices apply)

### CODE REVIEW

**Comment by mfranzke** [comment]
@nmerget shouldn't this lead to that https://db-ui.github.io/mono/review/fix-patternhub-redirect-404/components/button/?page=state redirects to https://db-ui.github.io/mono/review/fix-patternhub-redirect-404/components/button/overview?page=state, which it doesn't at the moment.

**Comment by mfranzke** [comment]
@nmerget https://db-ui.github.io/mono/review/fix-patternhub-redirect-404/components/button/?page=state still doesn't work.

**Comment by nmerget** [comment]
https://db-ui.github.io/mono/review/fix-patternhub-redirect-404/components/button/?page=state 

This is not a vaild URL. And the Marketingportal is not using this, so we are fine here

**Comment by mfranzke** [comment]
> https://db-ui.github.io/mono/review/fix-patternhub-redirect-404/components/button/?page=state

https://db-ui.github.io/mono/review/fix-patternhub-redirect-404/components/button/?page=state -> this actually is a valid URL

**Review by mfranzke — APPROVED** [review]

**Pull request merged**
