### PR TITLE
refactor: updated `actions/github-script`

### PR DESCRIPTION
**Pull request by mfranzke**
## Proposed changes

Resolves https://github.com/db-ui/mono/issues/2375

## Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Refactoring (fix on existing components or architectural decisions)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation Update (if none of the other choices apply)

### CODE REVIEW

**Comment by mfranzke** [comment]
@nmerget there are two new features based on the [changelog](https://github.com/actions/github-script/releases/tag/v7.0.0) – as you're much more aware of the pipeline implementation, is there something that we need to further change on this PR?

**Comment by nmerget** [comment]
> @nmerget there are two new features based on the [changelog](https://github.com/actions/github-script/releases/tag/v7.0.0) – as you're much more aware of the pipeline implementation, is there something that we need to further change on this PR?

It's fine, the changes won't affect us besides node20

**Comment by mfranzke** [comment]
> > @nmerget there are two new features based on the [changelog](https://github.com/actions/github-script/releases/tag/v7.0.0) – as you're much more aware of the pipeline implementation, is there something that we need to further change on this PR?
> 
> It's fine, the changes won't affect us besides node20

okay, in other words, would we profit somehow by adapting our code to these new features?

**Comment by nmerget** [comment]
> > > @nmerget there are two new features based on the [changelog](https://github.com/actions/github-script/releases/tag/v7.0.0) – as you're much more aware of the pipeline implementation, is there something that we need to further change on this PR?
> > 
> > 
> > It's fine, the changes won't affect us besides node20
> 
> @nmerget okay, in other words, would we profit somehow by adapting our code to these new features, or wouldn't they be of any need for us?

We don't have the need, if the pipeline runs it's okay. We can check in the future if we can improve it somehow

**Comment by mfranzke** [comment]
> > > > @nmerget there are two new features based on the [changelog](https://github.com/actions/github-script/releases/tag/v7.0.0) – as you're much more aware of the pipeline implementation, is there something that we need to further change on this PR?
> > > 
> > > 
> > > It's fine, the changes won't affect us besides node20
> > 
> > 
> > @nmerget okay, in other words, would we profit somehow by adapting our code to these new features, or wouldn't they be of any need for us?
> 
> We don't have the need, if the pipeline runs it's okay. We can check in the future if we can improve it somehow

why not today?

**Comment by nmerget** [comment]
> > > > > @nmerget there are two new features based on the [changelog](https://github.com/actions/github-script/releases/tag/v7.0.0) – as you're much more aware of the pipeline implementation, is there something that we need to further change on this PR?
> > > > 
> > > > 
> > > > It's fine, the changes won't affect us besides node20
> > > 
> > > 
> > > @nmerget okay, in other words, would we profit somehow by adapting our code to these new features, or wouldn't they be of any need for us?
> > 
> > 
> > We don't have the need, if the pipeline runs it's okay. We can check in the future if we can improve it somehow
> 
> why not today? what would be (another) trigger in the future ?

Because we want to release a beta version? If you have time for it, do it ;)

**Comment by mfranzke** [comment]
fixed with https://github.com/db-ui/mono/pull/2837

**Pull request closed without merging**
